services:
  api:
    image: portfolio-api
    container_name: portfolio-api
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "${API_PORT}:3000"
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/.env:/usr/src/app/.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_URL=http://localhost:${API_PORT}
      - APP_URL=http://localhost:${APP_PORT}
      - CHOKIDAR_USEPOLLING=true
  app:
    image: portfolio-app
    container_name: portfolio-app
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "${APP_PORT}:4200"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_URL=http://localhost:${API_PORT}
      - APP_URL=http://localhost:${APP_PORT}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
